#! /usr/bin/env bash

set -ex
uv version --bump $1
uv lock
VERSION=$(uv version --short)

git commit uv.lock pyproject.toml -m "Bump version to $VERSION"

git tag -a "v$VERSION" -m "Release version $VERSION"

git push
git push --tags
